title: Sylvia Nwakanma
logo: /assets/img/profile_drawing.png
description: "Working portfolio featuring <br> | Digital Mapping <br> | Coding <br> | Data Analysis <br> | Technical Writting <br><br>"
show_downloads: false
is_project_page: false
theme: jekyll-theme-minimal
