title: Sylvia Nwakanma
logo: /assets/img/profile_drawing.png
description: "Working portfolio featuring data analytic and map-making projects <br> | project0 <br> | project1 <br> | project2 <br><br>"
show_downloads: false
is_project_page: false
theme: jekyll-theme-minimal
