title: Sylvia Nwakanma
logo: /assets/img/profile_drawing.png
description: "Working portfolio featuring data analytic and map-making projects. \n -project1 \n -project2" 
show_downloads: false
is_project_page: false
theme: jekyll-theme-minimal
